"""Irish-style payslips in HTML (stored) and PDF (generated on demand)."""

from __future__ import annotations

import io
from decimal import Decimal

from jinja2 import Environment, select_autoescape
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle
from sqlalchemy import select
from sqlalchemy.orm import Session, selectinload

from app.core.security import mask_ppsn
from app.db.models import Company, Employee, PayrollResultRecord, PayrollRun, Payslip
from app.engine.money import D
from app.services.audit import audit

_env = Environment(autoescape=select_autoescape(["html"]))


def eur(v) -> str:
    return f"€{D(v):,.2f}"


_env.filters["eur"] = eur

TEMPLATE = _env.from_string("""<!doctype html><html><head><meta charset="utf-8"><title>Payslip {{ emp.employee_number }}</title>
<style>
body{font-family:Inter,Segoe UI,Arial,sans-serif;color:#1f2937;max-width:820px;margin:24px auto;padding:0 16px}
.hdr{display:flex;justify-content:space-between;border-bottom:3px solid #0f766e;padding-bottom:12px}
.hdr h1{margin:0;font-size:20px;color:#0f766e}.muted{color:#6b7280;font-size:12px}
.grid{display:grid;grid-template-columns:1fr 1fr;gap:16px;margin-top:16px}
table{width:100%;border-collapse:collapse;font-size:13px}th,td{padding:6px 8px;border-bottom:1px solid #e5e7eb;text-align:left}
td.n,th.n{text-align:right;font-variant-numeric:tabular-nums}th{background:#f0fdfa;color:#134e4a}
.net{margin-top:16px;background:#0f766e;color:#fff;padding:14px 18px;border-radius:8px;display:flex;justify-content:space-between;font-size:18px}
.box{border:1px solid #e5e7eb;border-radius:8px;padding:12px}
</style></head><body>
<div class="hdr"><div><h1>{{ company.trading_name or company.legal_name }}</h1>
<div class="muted">{{ company.legal_name }} · Employer reg. {{ company.tax_registration_number }}<br>{{ company.address or '' }}</div></div>
<div style="text-align:right"><b>PAYSLIP</b><div class="muted">Period {{ run.payroll_period }} ({{ run.frequency|lower }}) · Tax year {{ run.tax_year }}<br>
{{ run.period_start }} – {{ run.period_end }}<br>Payment date <b>{{ run.payment_date }}</b></div></div></div>
<div class="grid"><div class="box"><b>{{ emp.first_name }} {{ emp.last_name }}</b><div class="muted">
Employee no. {{ emp.employee_number }}<br>PPSN {{ ppsn }}<br>Employment ID {{ emp.employment_id or '—' }}<br>
Department {{ emp.department.name if emp.department else '—' }}</div></div>
<div class="box"><div class="muted">Tax basis <b>{{ r.tax_basis_applied }}</b><br>USC status <b>{{ r.usc_status_applied }}</b><br>
PRSI class <b>{{ r.prsi_subclass }}</b> · insurable weeks {{ r.insurable_weeks }}<br>
Tax credits (period / cumulative) {{ r.tax_credits|eur }}</div></div></div>
<div class="grid"><div><table><tr><th>Payments</th><th class="n">Amount</th></tr>
{% for e in earnings %}<tr><td>{{ e.description }}</td><td class="n">{{ e.amount|eur }}</td></tr>{% endfor %}
{% if r.bik|float > 0 %}<tr><td><i>Benefit in kind (notional, not paid)</i></td><td class="n"><i>{{ r.bik|eur }}</i></td></tr>{% endif %}
<tr><th>Gross pay</th><th class="n">{{ r.gross_pay|eur }}</th></tr></table></div>
<div><table><tr><th>Deductions</th><th class="n">Amount</th></tr>
{% for d in deductions %}<tr><td>{{ d.description }}</td><td class="n">{{ d.amount|eur }}</td></tr>{% endfor %}
<tr><th>Total deductions</th><th class="n">{{ total_ded|eur }}</th></tr></table></div></div>
<div class="net"><span>Net pay</span><b>{{ r.net_pay|eur }}</b></div>
<div class="grid"><div><table><tr><th>Year to date</th><th class="n"></th></tr>
{% for k, v in ytd %}<tr><td>{{ k }}</td><td class="n">{{ v|eur }}</td></tr>{% endfor %}</table></div>
<div><table><tr><th>Employer contributions</th><th class="n"></th></tr>
<tr><td>Employer PRSI</td><td class="n">{{ r.prsi_er|eur }}</td></tr>
<tr><td>Employer pension</td><td class="n">{{ r.pension_er|eur }}</td></tr>
<tr><th>Pay for tax / USC / PRSI</th><th class="n"></th></tr>
<tr><td>Pay for income tax</td><td class="n">{{ r.pay_for_tax|eur }}</td></tr>
<tr><td>Pay for USC</td><td class="n">{{ r.pay_for_usc|eur }}</td></tr>
<tr><td>Pay for PRSI</td><td class="n">{{ r.pay_for_prsi|eur }}</td></tr></table></div></div>
<p class="muted">Figures calculated under rule set(s) {{ rule_sets }}. Generated by Irish Payroll Management &amp; Compliance System (portfolio prototype - synthetic data).</p>
</body></html>""")


def _context(session: Session, result: PayrollResultRecord):
    run = session.get(PayrollRun, result.payroll_run_id)
    emp = session.scalar(select(Employee).where(Employee.employee_id == result.employee_id)
                         .options(selectinload(Employee.department)))
    company = session.get(Company, run.company_id)
    y = result.ytd or {}
    ytd = [("Gross pay", y.get("gross", 0)), ("Pay for tax", y.get("pay_for_tax", 0)), ("PAYE", y.get("tax", 0)),
           ("USC", y.get("usc", 0)), ("Employee PRSI", y.get("prsi_ee", 0)), ("LPT", y.get("lpt", 0)),
           ("Pension (employee)", y.get("pension_ee", 0)), ("Net pay", y.get("net", 0))]
    deds = [d for d in result.result_deductions if d.amount != 0 or d.code in ("PAYE", "USC", "PRSI_EE")]
    # show refunds as negative PAYE/USC lines
    deds_view = []
    for d in deds:
        amt = d.amount
        if d.code == "PAYE" and result.paye < 0:
            amt = result.paye
        if d.code == "USC" and result.usc < 0:
            amt = result.usc
        deds_view.append({"description": d.description, "amount": amt})
    total_ded = sum((D(x["amount"]) for x in deds_view), Decimal(0))
    rule_sets = sorted({r.split("-")[1] for r in (result.rules_used or []) if "-" in r})
    return dict(run=run, emp=emp, company=company, r=result, ppsn=mask_ppsn(emp.ppsn),
                earnings=[{"description": e["description"], "amount": e["amount"]} for e in (result.earnings_detail or [])],
                deductions=deds_view, total_ded=total_ded, ytd=ytd, rule_sets=", ".join(f"IE-{s}" for s in rule_sets))


def render_html(session: Session, result: PayrollResultRecord) -> str:
    return TEMPLATE.render(**_context(session, result))


def generate_payslips(session: Session, user, run: PayrollRun) -> int:
    if run.status not in ("APPROVED", "SUBMITTED", "COMPLETED"):
        raise ValueError("Payslips are generated only for approved payroll.")
    results = session.scalars(select(PayrollResultRecord).where(
        PayrollResultRecord.payroll_run_id == run.payroll_run_id, PayrollResultRecord.status == "CALCULATED")
        .options(selectinload(PayrollResultRecord.result_deductions))).all()
    existing = {p.result_id: p for p in session.scalars(select(Payslip).where(Payslip.payroll_run_id == run.payroll_run_id))}
    n = 0
    for r in results:
        html = render_html(session, r)
        if r.result_id in existing:
            existing[r.result_id].html = html
        else:
            session.add(Payslip(result_id=r.result_id, employee_id=r.employee_id, payroll_run_id=run.payroll_run_id, html=html))
        n += 1
    audit(session, user, "PAYSLIPS_GENERATED", "payroll_run", run.payroll_run_id, None, {"payslips": n})
    session.flush()
    return n


def render_pdf(session: Session, result: PayrollResultRecord) -> bytes:
    c = _context(session, result)
    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4, leftMargin=16 * mm, rightMargin=16 * mm, topMargin=14 * mm, bottomMargin=14 * mm,
                            title=f"Payslip {c['emp'].employee_number}")
    ss = getSampleStyleSheet()
    teal = colors.HexColor("#0f766e")
    story = [Paragraph(f"<font color='#0f766e'><b>{c['company'].trading_name or c['company'].legal_name}</b></font>", ss["Title"]),
             Paragraph(f"Payslip · Period {c['run'].payroll_period} ({c['run'].frequency.lower()}) · Tax year {c['run'].tax_year} · "
                       f"Paid {c['run'].payment_date}", ss["Normal"]),
             Paragraph(f"{c['emp'].first_name} {c['emp'].last_name} · Emp. no. {c['emp'].employee_number} · PPSN {c['ppsn']} · "
                       f"Basis {result.tax_basis_applied} · USC {result.usc_status_applied} · PRSI {result.prsi_subclass}", ss["Normal"]),
             Spacer(1, 6 * mm)]
    rows = [["Payments", "", "Deductions", ""]]
    left = [(e["description"], eur(e["amount"])) for e in c["earnings"]]
    right = [(d["description"], eur(d["amount"])) for d in c["deductions"]]
    for i in range(max(len(left), len(right))):
        a = left[i] if i < len(left) else ("", "")
        b = right[i] if i < len(right) else ("", "")
        rows.append([a[0], a[1], b[0], b[1]])
    rows.append(["Gross pay", eur(result.gross_pay), "Total deductions", eur(c["total_ded"])])
    rows.append(["BIK (notional, not paid)" if result.bik else "", eur(result.bik) if result.bik else "", "NET PAY",
                 eur(result.net_pay)])
    t = Table(rows, colWidths=[55 * mm, 30 * mm, 55 * mm, 30 * mm])
    t.setStyle(TableStyle([("BACKGROUND", (0, 0), (-1, 0), teal), ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                           ("ALIGN", (1, 0), (1, -1), "RIGHT"), ("ALIGN", (3, 0), (3, -1), "RIGHT"),
                           ("LINEBELOW", (0, 0), (-1, -1), 0.25, colors.lightgrey),
                           ("FONTNAME", (0, -2), (-1, -1), "Helvetica-Bold"),
                           ("BACKGROUND", (2, -1), (-1, -1), colors.HexColor("#ccfbf1"))]))
    story += [t, Spacer(1, 6 * mm)]
    ytd_rows = [["Year to date", ""]] + [[k, eur(v)] for k, v in c["ytd"]]
    er_rows = [["Employer", ""], ["Employer PRSI", eur(result.prsi_er)], ["Employer pension", eur(result.pension_er)],
               ["Pay for tax", eur(result.pay_for_tax)], ["Pay for USC", eur(result.pay_for_usc)],
               ["Pay for PRSI", eur(result.pay_for_prsi)]]
    sub_style = TableStyle([("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"), ("TEXTCOLOR", (0, 0), (-1, 0), teal),
                            ("ALIGN", (1, 0), (1, -1), "RIGHT"), ("LINEBELOW", (0, 0), (-1, 0), 0.5, teal)])
    t2 = Table([[Table(ytd_rows, colWidths=[45 * mm, 30 * mm], style=sub_style),
                 Table(er_rows, colWidths=[45 * mm, 30 * mm], style=sub_style)]], colWidths=[85 * mm, 85 * mm])
    t2.setStyle(TableStyle([("VALIGN", (0, 0), (-1, -1), "TOP")]))
    story += [t2, Spacer(1, 4 * mm),
              Paragraph(f"<font size=7 color='grey'>Rule sets {c['rule_sets']}. Portfolio prototype - synthetic data.</font>", ss["Normal"])]
    doc.build(story)
    audit(session, None, "PAYSLIP_PDF_GENERATED", "payroll_result", result.result_id)
    return buf.getvalue()
