"""initial schema

Revision ID: 2f5d189200c1
Revises: 
Create Date: 2026-09-22 00:18:01.382121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2f5d189200c1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bik_rules',
    sa.Column('rule_id', sa.String(length=60), nullable=False),
    sa.Column('rule_set_id', sa.String(length=20), nullable=False),
    sa.Column('jurisdiction', sa.String(length=4), nullable=False),
    sa.Column('tax_year', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('parameter', sa.String(length=80), nullable=False),
    sa.Column('value', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('source_authority', sa.String(length=120), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('source_document', sa.Text(), nullable=False),
    sa.Column('verified_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('rule_id', name=op.f('pk_bik_rules'))
    )
    with op.batch_alter_table('bik_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bik_rules_rule_set_id'), ['rule_set_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bik_rules_tax_year'), ['tax_year'], unique=False)

    op.create_table('companies',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('legal_name', sa.String(length=200), nullable=False),
    sa.Column('trading_name', sa.String(length=200), nullable=True),
    sa.Column('tax_registration_number', sa.String(length=20), nullable=False),
    sa.Column('employer_registration_details', sa.Text(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('contact_email', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('payroll_frequency', sa.String(length=20), nullable=False),
    sa.Column('financial_year', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('company_id', name=op.f('pk_companies')),
    sa.UniqueConstraint('tax_registration_number', name=op.f('uq_companies_tax_registration_number'))
    )
    op.create_table('lpt_rules',
    sa.Column('rule_id', sa.String(length=60), nullable=False),
    sa.Column('rule_set_id', sa.String(length=20), nullable=False),
    sa.Column('jurisdiction', sa.String(length=4), nullable=False),
    sa.Column('tax_year', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('parameter', sa.String(length=80), nullable=False),
    sa.Column('value', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('source_authority', sa.String(length=120), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('source_document', sa.Text(), nullable=False),
    sa.Column('verified_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('rule_id', name=op.f('pk_lpt_rules'))
    )
    with op.batch_alter_table('lpt_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lpt_rules_rule_set_id'), ['rule_set_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lpt_rules_tax_year'), ['tax_year'], unique=False)

    op.create_table('pension_rules',
    sa.Column('rule_id', sa.String(length=60), nullable=False),
    sa.Column('rule_set_id', sa.String(length=20), nullable=False),
    sa.Column('jurisdiction', sa.String(length=4), nullable=False),
    sa.Column('tax_year', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('parameter', sa.String(length=80), nullable=False),
    sa.Column('value', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('source_authority', sa.String(length=120), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('source_document', sa.Text(), nullable=False),
    sa.Column('verified_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('rule_id', name=op.f('pk_pension_rules'))
    )
    with op.batch_alter_table('pension_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pension_rules_rule_set_id'), ['rule_set_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pension_rules_tax_year'), ['tax_year'], unique=False)

    op.create_table('prsi_rules',
    sa.Column('rule_id', sa.String(length=60), nullable=False),
    sa.Column('rule_set_id', sa.String(length=20), nullable=False),
    sa.Column('jurisdiction', sa.String(length=4), nullable=False),
    sa.Column('tax_year', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('parameter', sa.String(length=80), nullable=False),
    sa.Column('value', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('source_authority', sa.String(length=120), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('source_document', sa.Text(), nullable=False),
    sa.Column('verified_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('rule_id', name=op.f('pk_prsi_rules'))
    )
    with op.batch_alter_table('prsi_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prsi_rules_rule_set_id'), ['rule_set_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prsi_rules_tax_year'), ['tax_year'], unique=False)

    op.create_table('roles',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('permissions', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('role_id', name=op.f('pk_roles')),
    sa.UniqueConstraint('code', name=op.f('uq_roles_code'))
    )
    op.create_table('tax_rules',
    sa.Column('rule_id', sa.String(length=60), nullable=False),
    sa.Column('rule_set_id', sa.String(length=20), nullable=False),
    sa.Column('jurisdiction', sa.String(length=4), nullable=False),
    sa.Column('tax_year', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('parameter', sa.String(length=80), nullable=False),
    sa.Column('value', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('source_authority', sa.String(length=120), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('source_document', sa.Text(), nullable=False),
    sa.Column('verified_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('rule_id', name=op.f('pk_tax_rules'))
    )
    with op.batch_alter_table('tax_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tax_rules_rule_set_id'), ['rule_set_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tax_rules_tax_year'), ['tax_year'], unique=False)

    op.create_table('usc_rules',
    sa.Column('rule_id', sa.String(length=60), nullable=False),
    sa.Column('rule_set_id', sa.String(length=20), nullable=False),
    sa.Column('jurisdiction', sa.String(length=4), nullable=False),
    sa.Column('tax_year', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('parameter', sa.String(length=80), nullable=False),
    sa.Column('value', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('source_authority', sa.String(length=120), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('source_document', sa.Text(), nullable=False),
    sa.Column('verified_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('rule_id', name=op.f('pk_usc_rules'))
    )
    with op.batch_alter_table('usc_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usc_rules_rule_set_id'), ['rule_set_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_usc_rules_tax_year'), ['tax_year'], unique=False)

    op.create_table('departments',
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('cost_centre', sa.String(length=20), nullable=True),
    sa.Column('monthly_budget', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], name=op.f('fk_departments_company_id_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('department_id', name=op.f('pk_departments')),
    sa.UniqueConstraint('company_id', 'name', name=op.f('uq_departments_company_id'))
    )
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_departments_company_id'), ['company_id'], unique=False)

    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=40), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['role'], ['roles.code'], name=op.f('fk_users_role_roles')),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('employees',
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('employee_number', sa.String(length=20), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('ppsn', sa.String(length=10), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('employment_start_date', sa.Date(), nullable=False),
    sa.Column('employment_end_date', sa.Date(), nullable=True),
    sa.Column('employment_status', sa.String(length=20), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('job_title', sa.String(length=120), nullable=True),
    sa.Column('location', sa.String(length=120), nullable=True),
    sa.Column('contract_type', sa.String(length=40), nullable=True),
    sa.Column('salary_type', sa.String(length=10), nullable=False),
    sa.Column('annual_salary', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('hourly_rate', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('standard_hours', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('pay_frequency', sa.String(length=20), nullable=False),
    sa.Column('prsi_class', sa.String(length=2), nullable=True),
    sa.Column('pension_scheme', sa.String(length=20), nullable=True),
    sa.Column('pension_ee_percent', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('pension_er_percent', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('employment_id', sa.String(length=20), nullable=True),
    sa.Column('bank_iban_masked', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("pay_frequency IN ('WEEKLY','FORTNIGHTLY','MONTHLY')", name=op.f('ck_employees_freq_valid')),
    sa.CheckConstraint("salary_type IN ('SALARY','HOURLY')", name=op.f('ck_employees_salary_type_valid')),
    sa.CheckConstraint('annual_salary IS NULL OR annual_salary >= 0', name=op.f('ck_employees_salary_non_negative')),
    sa.CheckConstraint('hourly_rate IS NULL OR hourly_rate >= 0', name=op.f('ck_employees_rate_non_negative')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], name=op.f('fk_employees_company_id_companies')),
    sa.ForeignKeyConstraint(['department_id'], ['departments.department_id'], name=op.f('fk_employees_department_id_departments')),
    sa.PrimaryKeyConstraint('employee_id', name=op.f('pk_employees')),
    sa.UniqueConstraint('company_id', 'employee_number', name=op.f('uq_employees_company_id'))
    )
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employees_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_employees_department_id'), ['department_id'], unique=False)

    op.create_table('payroll_audit_logs',
    sa.Column('audit_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_email', sa.String(length=200), nullable=True),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('entity', sa.String(length=60), nullable=False),
    sa.Column('entity_id', sa.String(length=60), nullable=True),
    sa.Column('before_value', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('after_value', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('fk_payroll_audit_logs_user_id_users')),
    sa.PrimaryKeyConstraint('audit_id', name=op.f('pk_payroll_audit_logs'))
    )
    with op.batch_alter_table('payroll_audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payroll_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_payroll_audit_logs_timestamp'), ['timestamp'], unique=False)

    op.create_table('payroll_runs',
    sa.Column('payroll_run_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('tax_year', sa.Integer(), nullable=False),
    sa.Column('payroll_period', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('frequency', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('run_type', sa.String(length=20), nullable=False),
    sa.Column('reverses_run_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('calculated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('totals', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('calc_seconds', sa.Float(), nullable=True),
    sa.CheckConstraint("status IN ('DRAFT','CALCULATING','VALIDATION_REQUIRED','READY_FOR_APPROVAL','APPROVED','SUBMITTED','COMPLETED','REVERSED')", name=op.f('ck_payroll_runs_status_valid')),
    sa.ForeignKeyConstraint(['approved_by'], ['users.user_id'], name=op.f('fk_payroll_runs_approved_by_users')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], name=op.f('fk_payroll_runs_company_id_companies')),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], name=op.f('fk_payroll_runs_created_by_users')),
    sa.ForeignKeyConstraint(['reverses_run_id'], ['payroll_runs.payroll_run_id'], name=op.f('fk_payroll_runs_reverses_run_id_payroll_runs')),
    sa.PrimaryKeyConstraint('payroll_run_id', name=op.f('pk_payroll_runs'))
    )
    with op.batch_alter_table('payroll_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payroll_runs_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payroll_runs_status'), ['status'], unique=False)
        batch_op.create_index('ix_run_company_period', ['company_id', 'tax_year', 'frequency', 'payroll_period'], unique=False)

    op.create_table('employee_benefits',
    sa.Column('benefit_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('benefit_type', sa.String(length=30), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('omv', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('co2_g_km', sa.Numeric(precision=6, scale=1), nullable=True),
    sa.Column('business_km', sa.Integer(), nullable=True),
    sa.Column('employee_contribution_annual', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('annual_value', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('period_value', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('active_from', sa.Date(), nullable=True),
    sa.Column('active_to', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], name=op.f('fk_employee_benefits_employee_id_employees'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('benefit_id', name=op.f('pk_employee_benefits'))
    )
    with op.batch_alter_table('employee_benefits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employee_benefits_employee_id'), ['employee_id'], unique=False)

    op.create_table('employee_tax_profiles',
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('tax_basis', sa.String(length=20), nullable=True),
    sa.Column('annual_tax_credits', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('annual_srcop', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('usc_status', sa.String(length=20), nullable=True),
    sa.Column('lpt_annual', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('prior_pay_for_tax', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('prior_tax', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('prior_usc_pay', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('prior_usc', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('rpn_number', sa.String(length=30), nullable=True),
    sa.Column('rpn_effective_date', sa.Date(), nullable=True),
    sa.Column('rpn_source', sa.String(length=40), nullable=True),
    sa.Column('rpn_imported_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], name=op.f('fk_employee_tax_profiles_employee_id_employees'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('profile_id', name=op.f('pk_employee_tax_profiles')),
    sa.UniqueConstraint('employee_id', name=op.f('uq_employee_tax_profiles_employee_id'))
    )
    op.create_table('payroll_exceptions',
    sa.Column('exception_id', sa.Integer(), nullable=False),
    sa.Column('payroll_run_id', sa.Integer(), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('resolved_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("severity IN ('INFO','WARNING','ERROR','CRITICAL')", name=op.f('ck_payroll_exceptions_severity_valid')),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], name=op.f('fk_payroll_exceptions_employee_id_employees')),
    sa.ForeignKeyConstraint(['payroll_run_id'], ['payroll_runs.payroll_run_id'], name=op.f('fk_payroll_exceptions_payroll_run_id_payroll_runs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.user_id'], name=op.f('fk_payroll_exceptions_resolved_by_users')),
    sa.PrimaryKeyConstraint('exception_id', name=op.f('pk_payroll_exceptions'))
    )
    with op.batch_alter_table('payroll_exceptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payroll_exceptions_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payroll_exceptions_payroll_run_id'), ['payroll_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payroll_exceptions_severity'), ['severity'], unique=False)

    op.create_table('payroll_inputs',
    sa.Column('input_id', sa.Integer(), nullable=False),
    sa.Column('payroll_run_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('insurable_weeks', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], name=op.f('fk_payroll_inputs_employee_id_employees')),
    sa.ForeignKeyConstraint(['payroll_run_id'], ['payroll_runs.payroll_run_id'], name=op.f('fk_payroll_inputs_payroll_run_id_payroll_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('input_id', name=op.f('pk_payroll_inputs')),
    sa.UniqueConstraint('payroll_run_id', 'employee_id', name=op.f('uq_payroll_inputs_payroll_run_id'))
    )
    with op.batch_alter_table('payroll_inputs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payroll_inputs_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payroll_inputs_payroll_run_id'), ['payroll_run_id'], unique=False)

    op.create_table('payroll_results',
    sa.Column('result_id', sa.Integer(), nullable=False),
    sa.Column('payroll_run_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('gross_pay', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('bik', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('pay_for_tax', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('pay_for_usc', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('pay_for_prsi', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('gross_tax', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('tax_credits', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('paye', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('usc', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('prsi_ee', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('prsi_er', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('prsi_class', sa.String(length=2), nullable=True),
    sa.Column('prsi_subclass', sa.String(length=4), nullable=True),
    sa.Column('insurable_weeks', sa.Integer(), nullable=False),
    sa.Column('lpt', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('pension_ee', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('pension_er', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('other_deductions', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('net_pay', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('employer_cost', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('statutory_liability', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('tax_basis_applied', sa.String(length=20), nullable=True),
    sa.Column('usc_status_applied', sa.String(length=20), nullable=True),
    sa.Column('ytd', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('trace', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('messages', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('rules_used', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('earnings_detail', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('error_code', sa.String(length=40), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('calculated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], name=op.f('fk_payroll_results_employee_id_employees')),
    sa.ForeignKeyConstraint(['payroll_run_id'], ['payroll_runs.payroll_run_id'], name=op.f('fk_payroll_results_payroll_run_id_payroll_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('result_id', name=op.f('pk_payroll_results')),
    sa.UniqueConstraint('payroll_run_id', 'employee_id', name=op.f('uq_payroll_results_payroll_run_id'))
    )
    with op.batch_alter_table('payroll_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payroll_results_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payroll_results_payroll_run_id'), ['payroll_run_id'], unique=False)

    op.create_table('revenue_submissions',
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('payroll_run_id', sa.Integer(), nullable=False),
    sa.Column('submission_ref', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('validation_errors', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('prepared_by', sa.Integer(), nullable=True),
    sa.Column('prepared_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['payroll_run_id'], ['payroll_runs.payroll_run_id'], name=op.f('fk_revenue_submissions_payroll_run_id_payroll_runs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prepared_by'], ['users.user_id'], name=op.f('fk_revenue_submissions_prepared_by_users')),
    sa.PrimaryKeyConstraint('submission_id', name=op.f('pk_revenue_submissions')),
    sa.UniqueConstraint('submission_ref', name=op.f('uq_revenue_submissions_submission_ref'))
    )
    with op.batch_alter_table('revenue_submissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_revenue_submissions_payroll_run_id'), ['payroll_run_id'], unique=False)

    op.create_table('rpn_records',
    sa.Column('rpn_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('tax_year', sa.Integer(), nullable=False),
    sa.Column('rpn_number', sa.String(length=30), nullable=False),
    sa.Column('employment_id', sa.String(length=20), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('tax_basis', sa.String(length=20), nullable=False),
    sa.Column('annual_tax_credits', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('annual_srcop', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('usc_status', sa.String(length=20), nullable=False),
    sa.Column('lpt_annual', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('prior_pay_for_tax', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('prior_tax', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('prior_usc_pay', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('prior_usc', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('imported_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], name=op.f('fk_rpn_records_employee_id_employees'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rpn_id', name=op.f('pk_rpn_records')),
    sa.UniqueConstraint('employee_id', 'rpn_number', name=op.f('uq_rpn_records_employee_id'))
    )
    with op.batch_alter_table('rpn_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rpn_records_employee_id'), ['employee_id'], unique=False)

    op.create_table('payroll_deductions',
    sa.Column('deduction_id', sa.Integer(), nullable=False),
    sa.Column('input_id', sa.Integer(), nullable=True),
    sa.Column('result_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.CheckConstraint('amount >= 0', name=op.f('ck_payroll_deductions_deduction_non_negative')),
    sa.ForeignKeyConstraint(['input_id'], ['payroll_inputs.input_id'], name=op.f('fk_payroll_deductions_input_id_payroll_inputs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['result_id'], ['payroll_results.result_id'], name=op.f('fk_payroll_deductions_result_id_payroll_results'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('deduction_id', name=op.f('pk_payroll_deductions'))
    )
    with op.batch_alter_table('payroll_deductions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payroll_deductions_input_id'), ['input_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payroll_deductions_result_id'), ['result_id'], unique=False)

    op.create_table('payroll_earnings',
    sa.Column('earning_id', sa.Integer(), nullable=False),
    sa.Column('input_id', sa.Integer(), nullable=False),
    sa.Column('earning_type', sa.String(length=30), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('hours', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('rate', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['input_id'], ['payroll_inputs.input_id'], name=op.f('fk_payroll_earnings_input_id_payroll_inputs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('earning_id', name=op.f('pk_payroll_earnings'))
    )
    with op.batch_alter_table('payroll_earnings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payroll_earnings_input_id'), ['input_id'], unique=False)

    op.create_table('payslips',
    sa.Column('payslip_id', sa.Integer(), nullable=False),
    sa.Column('result_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('payroll_run_id', sa.Integer(), nullable=False),
    sa.Column('html', sa.Text(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], name=op.f('fk_payslips_employee_id_employees')),
    sa.ForeignKeyConstraint(['payroll_run_id'], ['payroll_runs.payroll_run_id'], name=op.f('fk_payslips_payroll_run_id_payroll_runs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['result_id'], ['payroll_results.result_id'], name=op.f('fk_payslips_result_id_payroll_results'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('payslip_id', name=op.f('pk_payslips')),
    sa.UniqueConstraint('result_id', name=op.f('uq_payslips_result_id'))
    )
    with op.batch_alter_table('payslips', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payslips_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payslips_payroll_run_id'), ['payroll_run_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payslips', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payslips_payroll_run_id'))
        batch_op.drop_index(batch_op.f('ix_payslips_employee_id'))

    op.drop_table('payslips')
    with op.batch_alter_table('payroll_earnings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payroll_earnings_input_id'))

    op.drop_table('payroll_earnings')
    with op.batch_alter_table('payroll_deductions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payroll_deductions_result_id'))
        batch_op.drop_index(batch_op.f('ix_payroll_deductions_input_id'))

    op.drop_table('payroll_deductions')
    with op.batch_alter_table('rpn_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rpn_records_employee_id'))

    op.drop_table('rpn_records')
    with op.batch_alter_table('revenue_submissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_revenue_submissions_payroll_run_id'))

    op.drop_table('revenue_submissions')
    with op.batch_alter_table('payroll_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payroll_results_payroll_run_id'))
        batch_op.drop_index(batch_op.f('ix_payroll_results_employee_id'))

    op.drop_table('payroll_results')
    with op.batch_alter_table('payroll_inputs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payroll_inputs_payroll_run_id'))
        batch_op.drop_index(batch_op.f('ix_payroll_inputs_employee_id'))

    op.drop_table('payroll_inputs')
    with op.batch_alter_table('payroll_exceptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payroll_exceptions_severity'))
        batch_op.drop_index(batch_op.f('ix_payroll_exceptions_payroll_run_id'))
        batch_op.drop_index(batch_op.f('ix_payroll_exceptions_employee_id'))

    op.drop_table('payroll_exceptions')
    op.drop_table('employee_tax_profiles')
    with op.batch_alter_table('employee_benefits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employee_benefits_employee_id'))

    op.drop_table('employee_benefits')
    with op.batch_alter_table('payroll_runs', schema=None) as batch_op:
        batch_op.drop_index('ix_run_company_period')
        batch_op.drop_index(batch_op.f('ix_payroll_runs_status'))
        batch_op.drop_index(batch_op.f('ix_payroll_runs_company_id'))

    op.drop_table('payroll_runs')
    with op.batch_alter_table('payroll_audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payroll_audit_logs_timestamp'))
        batch_op.drop_index(batch_op.f('ix_payroll_audit_logs_action'))

    op.drop_table('payroll_audit_logs')
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employees_department_id'))
        batch_op.drop_index(batch_op.f('ix_employees_company_id'))

    op.drop_table('employees')
    op.drop_table('users')
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_departments_company_id'))

    op.drop_table('departments')
    with op.batch_alter_table('usc_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usc_rules_tax_year'))
        batch_op.drop_index(batch_op.f('ix_usc_rules_rule_set_id'))

    op.drop_table('usc_rules')
    with op.batch_alter_table('tax_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tax_rules_tax_year'))
        batch_op.drop_index(batch_op.f('ix_tax_rules_rule_set_id'))

    op.drop_table('tax_rules')
    op.drop_table('roles')
    with op.batch_alter_table('prsi_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prsi_rules_tax_year'))
        batch_op.drop_index(batch_op.f('ix_prsi_rules_rule_set_id'))

    op.drop_table('prsi_rules')
    with op.batch_alter_table('pension_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pension_rules_tax_year'))
        batch_op.drop_index(batch_op.f('ix_pension_rules_rule_set_id'))

    op.drop_table('pension_rules')
    with op.batch_alter_table('lpt_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lpt_rules_tax_year'))
        batch_op.drop_index(batch_op.f('ix_lpt_rules_rule_set_id'))

    op.drop_table('lpt_rules')
    op.drop_table('companies')
    with op.batch_alter_table('bik_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bik_rules_tax_year'))
        batch_op.drop_index(batch_op.f('ix_bik_rules_rule_set_id'))

    op.drop_table('bik_rules')
    # ### end Alembic commands ###
